# Generated by Django 5.2.9 on 2025-12-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_studyroom_pomodorosession'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroom',
            name='timer_duration',
            field=models.IntegerField(default=25),
        ),
    ]
